  
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true

ratings:
  paths:
  - "**.es6"

exclude_paths:
  - "**.md"
  - "**.html"
  - "**.json"
  - "**.css"
  - "LICENSE"

exclude_patterns:
  - "tailwind.js"
  - "styles/tailwind.css"
  - "src/serviceWorker.js"